export const AVAILABLE_ONLY = "AVAILABLE_ONLY";
export const NONSTOP_ONLY = "NONSTOP_ONLY";
export const SET_TOKEN = "SET_TOKEN";
export const SET_USER_INFO = "SET_USER_INFO";
export const PUSH_NOTIFICATION = "PUSH_NOTIFICATION";
export const CLEAR_NOTIFICATION = "CLEAR_NOTIFICATION";